export interface Service {
  id: string
  title: string
  subtitle: string
  description: string[]
  included: string[]
  whyChooseUs: string[]
  idealFor: string[]
  images: string[]
  ctaText: string
}

export const services: Service[] = [
  {
    id: "smart-heating",
    title: "Smart Heating Control",
    subtitle: "Intelligent Heating Control for Modern Properties",
    description: [
      "Take control of your heating with a professionally installed smart thermostat. Ideal for homeowners, landlords, and property managers looking to improve efficiency and reduce running costs.",
      "At Swiftfix Plumbing & Heating, we supply and install leading smart controls including Hive and other trusted UK brands — all installed safely and correctly by a Gas Safe registered engineer.",
      "Smart heating is no longer a luxury — it's an essential upgrade for modern rental properties.",
    ],
    included: [
      "Safe wiring and boiler integration",
      "Receiver fitting and full configuration",
      "Heating & hot water system testing",
      "Setup assistance and app connection",
      "Compliance with UK safety regulations",
    ],
    whyChooseUs: [
      "Control your heating remotely from anywhere",
      "Reduce unnecessary energy usage",
      "Lower monthly heating bills",
      "Improve tenant comfort",
      "Boost property energy efficiency (EPC support)",
      "Wireless options with minimal disruption",
    ],
    idealFor: [
      "Rental properties",
      "Estate agents",
      "HMO properties",
      "Boiler upgrades",
      "System improvements",
    ],
    images: ["/services/smart-heating.jpg"],
    ctaText: "Book Your Installation",
  },
  {
    id: "boiler-installation",
    title: "Boiler Installation",
    subtitle: "Professional Boiler Installation in London",
    description: [
      "Upgrade your heating system with a high-efficiency boiler installed by a fully qualified Gas Safe registered engineer.",
      "At Swiftfix Plumbing & Heating, we supply and install trusted German-engineered and UK-leading boiler brands including Vaillant and Glow-worm. Whether you're replacing an old, unreliable boiler or upgrading for better efficiency, we deliver safe, compliant and long-lasting installations.",
    ],
    included: [
      "Removal and safe disposal of old boiler",
      "Professional installation of new high-efficiency boiler",
      "System flush (if required)",
      "Magnetic filter installation (recommended)",
      "Full system testing",
      "Gas Safe certification",
      "Manufacturer warranty registration",
    ],
    whyChooseUs: [
      "Gas Safe Registered",
      "Ideal for landlords & estate agents",
      "Honest pricing — no hidden extras",
      "Clean and tidy workmanship",
      "Warranty support",
      "Emergency response available",
    ],
    idealFor: [
      "Boiler replacements",
      "Rental property upgrades",
      "System conversions (heat-only to combi)",
      "Energy efficiency improvements",
      "Faulty or unreliable boilers",
    ],
    images: [
      "/services/boiler-install-1.jpg",
      "/services/boiler-install-2.jpg",
      "/services/boiler-install-3.jpg",
      "/services/boiler-install-4.jpg",
      "/services/boiler-install-5.jpg",
      "/services/boiler-install-6.jpg",
    ],
    ctaText: "Get a Free Boiler Quote",
  },
  {
    id: "plumbing",
    title: "Plumbing Services",
    subtitle: "Professional Plumbing for Homes & Landlords",
    description: [
      "Professional plumbing services for homeowners, landlords and estate agents across London and surrounding areas.",
      "At Swiftfix Plumbing & Heating, we provide reliable, high-quality plumbing solutions carried out with care, precision and full transparency on pricing.",
      "No job is too small. Every job is completed to a professional standard.",
    ],
    included: [
      "Leak detection & repairs",
      "Tap repairs & replacements",
      "Toilet repairs & installations",
      "Basin & sink installations",
      "Shower replacements",
      "Radiator repairs & replacements",
      "Pipework repairs & upgrades",
      "Bathroom plumbing",
      "Kitchen plumbing",
      "Fault finding & system diagnostics",
    ],
    whyChooseUs: [
      "Clean and tidy work",
      "Long-lasting repairs",
      "Clear communication",
      "Honest pricing",
      "Respect for your property",
    ],
    idealFor: [
      "Homeowners",
      "Rental properties",
      "Estate agents",
      "Property management companies",
      "Ongoing maintenance contracts",
    ],
    images: ["/services/plumbing-1.jpg", "/services/plumbing-2.jpg"],
    ctaText: "Book a Plumbing Service",
  },
  {
    id: "gas-safety",
    title: "Gas Safety (CP12)",
    subtitle: "Landlord Gas Safety Certificate",
    description: [
      "Stay compliant. Protect your tenants. Avoid penalties.",
      "If you are a landlord, UK law requires you to obtain a valid Gas Safety Certificate every 12 months for all rental properties with gas appliances.",
      "At Swiftfix Plumbing & Heating, we carry out thorough gas safety inspections and issue official CP12 certificates quickly and professionally.",
      "We understand deadlines and tenant coordination — we make the process simple and stress-free.",
    ],
    included: [
      "Full inspection of all gas appliances",
      "Boiler safety check",
      "Gas pipework inspection",
      "Flue and ventilation checks",
      "Tightness test",
      "Safety and compliance confirmation",
      "Digital CP12 certificate issued",
    ],
    whyChooseUs: [
      "Fully Gas Safe Registered",
      "Experienced with rental properties",
      "Fast booking availability",
      "Ideal for estate agents & property managers",
      "Clear communication & reporting",
      "Competitive pricing",
    ],
    idealFor: [
      "Private landlords",
      "HMO property owners",
      "Letting agents",
      "Property management companies",
      "Portfolio landlords",
    ],
    images: [
      "/services/gas-safety-1.jpg",
      "/services/gas-safety-2.jpg",
      "/services/gas-safety-3.jpg",
    ],
    ctaText: "Book Gas Safety Inspection",
  },
  {
    id: "boiler-service",
    title: "Boiler Servicing",
    subtitle: "Boiler Service & Maintenance",
    description: [
      "Keep your boiler running safely, efficiently and reliably.",
      "Regular boiler servicing is essential to ensure your heating system operates safely and efficiently. Annual servicing can help prevent unexpected breakdowns, improve energy efficiency and extend the lifespan of your boiler.",
      "At Swiftfix Plumbing & Heating, we provide professional boiler servicing for homeowners, landlords and property managers.",
      "Regular servicing can also identify potential problems before they become costly repairs.",
    ],
    included: [
      "Full visual inspection of the boiler",
      "Gas pressure and combustion checks",
      "Flue and ventilation inspection",
      "Safety device testing",
      "Internal component inspection",
      "Cleaning of key components",
      "Performance testing",
    ],
    whyChooseUs: [
      "Prevent unexpected breakdowns",
      "Improve heating efficiency",
      "Reduce energy bills",
      "Maintain manufacturer warranty",
      "Ensure safe operation",
    ],
    idealFor: [
      "Homeowners",
      "Rental properties",
      "Estate agents",
      "Property management companies",
    ],
    images: ["/services/boiler-service-1.jpg", "/services/boiler-service-2.jpg"],
    ctaText: "Book Your Boiler Service",
  },
  {
    id: "power-flushing",
    title: "Power Flushing",
    subtitle: "Restore Your Heating System's Performance",
    description: [
      "Restore the performance of your heating system.",
      "Over time, central heating systems can build up sludge, rust and debris inside the pipework and radiators. This buildup can reduce heating efficiency, cause cold spots in radiators and place unnecessary strain on your boiler.",
      "At Swiftfix Plumbing & Heating, we provide professional power flushing services to clean your heating system and restore optimal performance.",
      "Your heating system will be left clean, balanced and operating efficiently.",
    ],
    included: [
      "Connection of professional flushing machine",
      "Circulation of cleaning chemicals through the system",
      "Individual radiator cleaning",
      "Sludge removal from pipework",
      "System neutralisation and refill",
      "Addition of corrosion inhibitor",
    ],
    whyChooseUs: [
      "Improved heating efficiency",
      "Faster radiator heat-up time",
      "Reduced energy bills",
      "Extended boiler lifespan",
      "Removal of sludge and debris",
      "Better system circulation",
    ],
    idealFor: [
      "Radiators cold at the bottom",
      "Some radiators not heating properly",
      "Boiler making unusual noises",
      "Dirty water when bleeding radiators",
      "Slow heating throughout the property",
      "Frequent boiler breakdowns",
    ],
    images: [
      "/services/power-flushing-1.jpg",
      "/services/power-flushing-2.jpg",
      "/services/power-flushing-3.jpg",
    ],
    ctaText: "Book a Power Flush",
  },
  {
    id: "bathroom-renovations",
    title: "Bathroom Renovations",
    subtitle: "Complete Professional Bathroom Renovation",
    description: [
      "Transform your bathroom with a complete professional renovation.",
      "At Swiftfix Plumbing & Heating, we provide full bathroom renovation services from start to finish. Whether you want to upgrade an outdated bathroom, renovate a rental property, or create a modern new space, our experienced team delivers high-quality workmanship and reliable project management.",
      "We handle the entire process from removal of the old bathroom to the final installation.",
    ],
    included: [
      "Full bathroom refurbishment",
      "Shower installation",
      "Bathtub installation or replacement",
      "Toilet installation",
      "Basin & vanity unit installation",
      "Wall & floor tiling",
      "Pipework replacement",
      "Radiator & towel rail installation",
      "Lighting & extractor fan installation",
      "Complete plumbing upgrades",
    ],
    whyChooseUs: [
      "Bathroom design consultation",
      "Removal of old bathroom fixtures",
      "Plumbing and pipework installation",
      "Tiling and wall preparation",
      "Installation of bathroom units",
      "Final finishing and testing",
    ],
    idealFor: [
      "Homeowners upgrading their bathroom",
      "Landlords renovating rental properties",
      "Estate agents preparing properties",
      "Property refurbishments",
      "Bathroom modernisation projects",
    ],
    images: [
      "/services/bathroom-1.jpg",
      "/services/bathroom-2.jpg",
      "/services/bathroom-3.jpg",
    ],
    ctaText: "Start Your Renovation",
  },
  {
    id: "emergency",
    title: "24/7 Emergency",
    subtitle: "Emergency Plumbing — 24/7 Call Out",
    description: [
      "Fast response. Immediate action. Damage control.",
      "When a plumbing emergency happens, every minute counts. At Swiftfix Plumbing & Heating, we provide rapid-response emergency plumbing services across London — day or night.",
      "We act quickly to isolate the problem, stop the leak, and prevent further property damage.",
    ],
    included: [
      "Available 24 hours a day, 7 days a week",
      "Fast response time",
      "Damage limitation focus",
      "Fully insured engineers",
      "Gas Safe Registered",
      "Transparent pricing — no hidden surprises",
    ],
    whyChooseUs: [
      "Standard Call Out: £70 (1-hour minimum)",
      "Out-of-hours rates apply",
      "Ideal for landlords & estate agents",
      "Immediate action on arrival",
    ],
    idealFor: [
      "Burst pipes",
      "Severe water leaks",
      "Ceiling leaks",
      "Flooding properties",
      "No water supply",
      "Overflowing toilets",
      "Major boiler leaks",
      "Urgent landlord call-outs",
    ],
    images: [],
    ctaText: "Call Now — 07767 848827",
  },
]
